name: pg_database
services:
    postgres:
        container_name: postgres_1
        ports:
            - 5432:5432
        environment:
            - POSTGRES_PASSWORD=postgres
        image: postgres
